// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Collector.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Collector.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __Canon__Collector__inject_name = "inject";

const ::std::string __Canon__Processor__init_name = "init";

const ::std::string __Canon__Processor__injectA_name = "injectA";

const ::std::string __Canon__Processor__injectB_name = "injectB";

const ::std::string __Canon__Frontend__multiply_name = "multiply";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::Canon::upCast(::IceProxy::Canon::Collector* p) { return p; }

void
::IceProxy::Canon::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Canon::Collector>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Canon::Collector;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Canon::Collector::inject(::Ice::Int index, const ::Canon::Matrix& result, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Canon__Collector__inject_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Canon::Collector* __del = dynamic_cast< ::IceDelegate::Canon::Collector*>(__delBase.get());
            __del->inject(index, result, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Canon::Collector::begin_inject(::Ice::Int index, const ::Canon::Matrix& result, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Canon__Collector__inject_name, __del, __cookie);
    try
    {
        __result->__prepare(__Canon__Collector__inject_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(index);
        __os->write(result);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Canon::Collector::end_inject(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Canon__Collector__inject_name);
}

const ::std::string&
IceProxy::Canon::Collector::ice_staticId()
{
    return ::Canon::Collector::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Canon::Collector::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Canon::Collector);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Canon::Collector::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Canon::Collector);
}

::IceProxy::Ice::Object*
IceProxy::Canon::Collector::__newInstance() const
{
    return new Collector;
}
::IceProxy::Ice::Object* ::IceProxy::Canon::upCast(::IceProxy::Canon::Processor* p) { return p; }

void
::IceProxy::Canon::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Canon::Processor>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Canon::Processor;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Canon::Processor::init(::Ice::Int index, ::Ice::Int order, const ::Canon::ProcessorPrx& above, const ::Canon::ProcessorPrx& left, const ::Canon::CollectorPrx& target, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Canon__Processor__init_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Canon::Processor* __del = dynamic_cast< ::IceDelegate::Canon::Processor*>(__delBase.get());
            __del->init(index, order, above, left, target, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Canon::Processor::begin_init(::Ice::Int index, ::Ice::Int order, const ::Canon::ProcessorPrx& above, const ::Canon::ProcessorPrx& left, const ::Canon::CollectorPrx& target, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Canon__Processor__init_name, __del, __cookie);
    try
    {
        __result->__prepare(__Canon__Processor__init_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(index);
        __os->write(order);
        __os->write(above);
        __os->write(left);
        __os->write(target);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Canon::Processor::end_init(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Canon__Processor__init_name);
}

void
IceProxy::Canon::Processor::injectA(const ::Canon::Matrix& a, ::Ice::Int step, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Canon__Processor__injectA_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Canon::Processor* __del = dynamic_cast< ::IceDelegate::Canon::Processor*>(__delBase.get());
            __del->injectA(a, step, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Canon::Processor::begin_injectA(const ::Canon::Matrix& a, ::Ice::Int step, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Canon__Processor__injectA_name, __del, __cookie);
    try
    {
        __result->__prepare(__Canon__Processor__injectA_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(a);
        __os->write(step);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Canon::Processor::end_injectA(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Canon__Processor__injectA_name);
}

void
IceProxy::Canon::Processor::injectB(const ::Canon::Matrix& b, ::Ice::Int step, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Canon__Processor__injectB_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Canon::Processor* __del = dynamic_cast< ::IceDelegate::Canon::Processor*>(__delBase.get());
            __del->injectB(b, step, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Canon::Processor::begin_injectB(const ::Canon::Matrix& b, ::Ice::Int step, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Canon__Processor__injectB_name, __del, __cookie);
    try
    {
        __result->__prepare(__Canon__Processor__injectB_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(b);
        __os->write(step);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Canon::Processor::end_injectB(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Canon__Processor__injectB_name);
}

const ::std::string&
IceProxy::Canon::Processor::ice_staticId()
{
    return ::Canon::Processor::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Canon::Processor::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Canon::Processor);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Canon::Processor::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Canon::Processor);
}

::IceProxy::Ice::Object*
IceProxy::Canon::Processor::__newInstance() const
{
    return new Processor;
}
::IceProxy::Ice::Object* ::IceProxy::Canon::upCast(::IceProxy::Canon::Frontend* p) { return p; }

void
::IceProxy::Canon::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Canon::Frontend>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Canon::Frontend;
        v->__copyFrom(proxy);
    }
}

::Canon::Matrix
IceProxy::Canon::Frontend::multiply(const ::Canon::Matrix& a, const ::Canon::Matrix& b, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Canon__Frontend__multiply_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__Canon__Frontend__multiply_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::Canon::Frontend* __del = dynamic_cast< ::IceDelegate::Canon::Frontend*>(__delBase.get());
            return __del->multiply(a, b, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Canon::Frontend::begin_multiply(const ::Canon::Matrix& a, const ::Canon::Matrix& b, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Canon__Frontend__multiply_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Canon__Frontend__multiply_name, __del, __cookie);
    try
    {
        __result->__prepare(__Canon__Frontend__multiply_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(a);
        __os->write(b);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Canon::Matrix
IceProxy::Canon::Frontend::end_multiply(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Canon__Frontend__multiply_name);
    ::Canon::Matrix __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::Canon::Frontend::ice_staticId()
{
    return ::Canon::Frontend::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Canon::Frontend::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Canon::Frontend);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Canon::Frontend::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Canon::Frontend);
}

::IceProxy::Ice::Object*
IceProxy::Canon::Frontend::__newInstance() const
{
    return new Frontend;
}

void
IceDelegateM::Canon::Collector::inject(::Ice::Int index, const ::Canon::Matrix& result, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Canon__Collector__inject_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(index);
        __os->write(result);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::Canon::Processor::init(::Ice::Int index, ::Ice::Int order, const ::Canon::ProcessorPrx& above, const ::Canon::ProcessorPrx& left, const ::Canon::CollectorPrx& target, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Canon__Processor__init_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(index);
        __os->write(order);
        __os->write(above);
        __os->write(left);
        __os->write(target);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::Canon::Processor::injectA(const ::Canon::Matrix& a, ::Ice::Int step, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Canon__Processor__injectA_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(a);
        __os->write(step);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::Canon::Processor::injectB(const ::Canon::Matrix& b, ::Ice::Int step, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Canon__Processor__injectB_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(b);
        __os->write(step);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

::Canon::Matrix
IceDelegateM::Canon::Frontend::multiply(const ::Canon::Matrix& a, const ::Canon::Matrix& b, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Canon__Frontend__multiply_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(a);
        __os->write(b);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::Canon::Matrix __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateD::Canon::Collector::inject(::Ice::Int index, const ::Canon::Matrix& result, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int __p_index, const ::Canon::Matrix& __p_result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_index(__p_index),
            _m_result(__p_result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Canon::Collector* servant = dynamic_cast< ::Canon::Collector*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->inject(_m_index, _m_result, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Ice::Int _m_index;
        const ::Canon::Matrix& _m_result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Canon__Collector__inject_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(index, result, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::Canon::Processor::init(::Ice::Int index, ::Ice::Int order, const ::Canon::ProcessorPrx& above, const ::Canon::ProcessorPrx& left, const ::Canon::CollectorPrx& target, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int __p_index, ::Ice::Int __p_order, const ::Canon::ProcessorPrx& __p_above, const ::Canon::ProcessorPrx& __p_left, const ::Canon::CollectorPrx& __p_target, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_index(__p_index),
            _m_order(__p_order),
            _m_above(__p_above),
            _m_left(__p_left),
            _m_target(__p_target)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Canon::Processor* servant = dynamic_cast< ::Canon::Processor*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->init(_m_index, _m_order, _m_above, _m_left, _m_target, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Ice::Int _m_index;
        ::Ice::Int _m_order;
        const ::Canon::ProcessorPrx& _m_above;
        const ::Canon::ProcessorPrx& _m_left;
        const ::Canon::CollectorPrx& _m_target;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Canon__Processor__init_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(index, order, above, left, target, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::Canon::Processor::injectA(const ::Canon::Matrix& a, ::Ice::Int step, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::Canon::Matrix& __p_a, ::Ice::Int __p_step, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_a(__p_a),
            _m_step(__p_step)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Canon::Processor* servant = dynamic_cast< ::Canon::Processor*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->injectA(_m_a, _m_step, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::Canon::Matrix& _m_a;
        ::Ice::Int _m_step;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Canon__Processor__injectA_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(a, step, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::Canon::Processor::injectB(const ::Canon::Matrix& b, ::Ice::Int step, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::Canon::Matrix& __p_b, ::Ice::Int __p_step, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_b(__p_b),
            _m_step(__p_step)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Canon::Processor* servant = dynamic_cast< ::Canon::Processor*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->injectB(_m_b, _m_step, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::Canon::Matrix& _m_b;
        ::Ice::Int _m_step;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Canon__Processor__injectB_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(b, step, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Canon::Matrix
IceDelegateD::Canon::Frontend::multiply(const ::Canon::Matrix& a, const ::Canon::Matrix& b, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Canon::Matrix& __result, const ::Canon::Matrix& __p_a, const ::Canon::Matrix& __p_b, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_a(__p_a),
            _m_b(__p_b)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Canon::Frontend* servant = dynamic_cast< ::Canon::Frontend*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->multiply(_m_a, _m_b, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Canon::Matrix& _result;
        const ::Canon::Matrix& _m_a;
        const ::Canon::Matrix& _m_b;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Canon__Frontend__multiply_name, ::Ice::Normal, __context);
    ::Canon::Matrix __result;
    try
    {
        _DirectI __direct(__result, a, b, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* Canon::upCast(::Canon::Collector* p) { return p; }

namespace
{
const ::std::string __Canon__Collector_ids[2] =
{
    "::Canon::Collector",
    "::Ice::Object"
};

}

bool
Canon::Collector::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Canon__Collector_ids, __Canon__Collector_ids + 2, _s);
}

::std::vector< ::std::string>
Canon::Collector::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Canon__Collector_ids[0], &__Canon__Collector_ids[2]);
}

const ::std::string&
Canon::Collector::ice_id(const ::Ice::Current&) const
{
    return __Canon__Collector_ids[0];
}

const ::std::string&
Canon::Collector::ice_staticId()
{
    return __Canon__Collector_ids[0];
}

::Ice::DispatchStatus
Canon::Collector::___inject(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Int index;
    ::Canon::Matrix result;
    __is->read(index);
    __is->read(result);
    __inS.endReadParams();
    inject(index, result, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Canon__Collector_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "inject"
};

}

::Ice::DispatchStatus
Canon::Collector::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Canon__Collector_all, __Canon__Collector_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Canon__Collector_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___inject(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Canon::Collector::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Canon::Collector::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Canon::__patch(CollectorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Canon::CollectorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Canon::Collector::ice_staticId(), v);
    }
}

::Ice::Object* Canon::upCast(::Canon::Processor* p) { return p; }

namespace
{
const ::std::string __Canon__Processor_ids[2] =
{
    "::Canon::Processor",
    "::Ice::Object"
};

}

bool
Canon::Processor::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Canon__Processor_ids, __Canon__Processor_ids + 2, _s);
}

::std::vector< ::std::string>
Canon::Processor::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Canon__Processor_ids[0], &__Canon__Processor_ids[2]);
}

const ::std::string&
Canon::Processor::ice_id(const ::Ice::Current&) const
{
    return __Canon__Processor_ids[0];
}

const ::std::string&
Canon::Processor::ice_staticId()
{
    return __Canon__Processor_ids[0];
}

::Ice::DispatchStatus
Canon::Processor::___init(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Int index;
    ::Ice::Int order;
    ::Canon::ProcessorPrx above;
    ::Canon::ProcessorPrx left;
    ::Canon::CollectorPrx target;
    __is->read(index);
    __is->read(order);
    __is->read(above);
    __is->read(left);
    __is->read(target);
    __inS.endReadParams();
    init(index, order, above, left, target, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Canon::Processor::___injectA(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Canon::Matrix a;
    ::Ice::Int step;
    __is->read(a);
    __is->read(step);
    __inS.endReadParams();
    injectA(a, step, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Canon::Processor::___injectB(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Canon::Matrix b;
    ::Ice::Int step;
    __is->read(b);
    __is->read(step);
    __inS.endReadParams();
    injectB(b, step, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Canon__Processor_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "init",
    "injectA",
    "injectB"
};

}

::Ice::DispatchStatus
Canon::Processor::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Canon__Processor_all, __Canon__Processor_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Canon__Processor_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___init(in, current);
        }
        case 5:
        {
            return ___injectA(in, current);
        }
        case 6:
        {
            return ___injectB(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Canon::Processor::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Canon::Processor::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Canon::__patch(ProcessorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Canon::ProcessorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Canon::Processor::ice_staticId(), v);
    }
}

::Ice::Object* Canon::upCast(::Canon::Frontend* p) { return p; }

namespace
{
const ::std::string __Canon__Frontend_ids[2] =
{
    "::Canon::Frontend",
    "::Ice::Object"
};

}

bool
Canon::Frontend::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Canon__Frontend_ids, __Canon__Frontend_ids + 2, _s);
}

::std::vector< ::std::string>
Canon::Frontend::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Canon__Frontend_ids[0], &__Canon__Frontend_ids[2]);
}

const ::std::string&
Canon::Frontend::ice_id(const ::Ice::Current&) const
{
    return __Canon__Frontend_ids[0];
}

const ::std::string&
Canon::Frontend::ice_staticId()
{
    return __Canon__Frontend_ids[0];
}

::Ice::DispatchStatus
Canon::Frontend::___multiply(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Canon::Matrix a;
    ::Canon::Matrix b;
    __is->read(a);
    __is->read(b);
    __inS.endReadParams();
    ::Canon::Matrix __ret = multiply(a, b, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Canon__Frontend_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "multiply"
};

}

::Ice::DispatchStatus
Canon::Frontend::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Canon__Frontend_all, __Canon__Frontend_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Canon__Frontend_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___multiply(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Canon::Frontend::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Canon::Frontend::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Canon::__patch(FrontendPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Canon::FrontendPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Canon::Frontend::ice_staticId(), v);
    }
}
